# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-27 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='keyphrase',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='entity',
            name='confidence',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
