# Generated by Django 2.1.1 on 2018-10-19 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=1000)),
                ('uploadDate', models.DateTimeField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Recordings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=1000)),
                ('uploadDate', models.DateTimeField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Transcriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=1000)),
                ('uploadDate', models.DateTimeField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=250)),
                ('userPassword', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='transcriptions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.User'),
        ),
        migrations.AddField(
            model_name='recordings',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.User'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.User'),
        ),
    ]
