# Generated by Django 2.1.1 on 2018-12-05 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_threadtask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='user',
        ),
        migrations.RemoveField(
            model_name='recordings',
            name='user',
        ),
        migrations.RemoveField(
            model_name='transcriptions',
            name='user',
        ),
    ]
